accounts/urls.py
from django.urls import path
from accounts.views import *

app_name='accounts'
urlpatterns = [
    path('',user_detail,name='user-detail-pk'),
    path("auth/users/<int:pk>", user_detail,name = 'user-detail-pk'),
    path("parties", user_detail,name = 'user-detail'),
    path('manage_party',manage_party,name='manage-party'),
    path('save_party',save_party,name='save-party'),
    path('manage_party/<int:pk>',manage_party,name='manage-party-pk'),
    path('delete_party/<int:pk>',delete_party,name='delete-party'),
    path('manage_transaction/<int:pk>/',manage_transaction,name='manage-transaction'),
    path('manage_transaction/',manage_transaction,name='manage-transaction'),
    path('save_transactions/', save_transaction, name='save-transaction'),
    path('transactions_list/',transaction_list, name='transaction_list'),
    path('delete_transaction/<int:pk>', delete_transaction, name='delete-transaction'),
    path('view_transactions/<int:pk>', view_transactions, name='view-transactions'),
    path('manage_sales_purchase',manage_sales_purchases,name='manage-sales-purchase'),
    path('manage_sales_purchase/<int:pk>/',manage_sales_purchases,name='manage-sales-purchase'),
    path('save_trade',save_trade,name="save-trade"),
    path('sales_list/',sales_list, name='sales_list'),
    path('purchases_list/',purchases_list, name='purchases_list'),
    path('products/',products,name="products"),
    path('products/<int:pk>',products,name="products-pk"),
    path('manage_products/',manage_products,name="manage-products"),
    path('manage_products/<int:pk>',manage_products,name="manage-products-pk"),
    path('save_products/',save_product,name="save-product"),
    path('delete_product/<int:pk>',delete_product,name="delete-product"),
    path('print/<int:pk>',print_veiw,name="print-view-pk"),
    path('manage_conversion/',conversion,name="conversion"),
    path('save_conversion/',save_conversion,name="save-conversion"),
    path('identifier/',check_identifier,name="check-id"),
    path('delete_conversion/<int:pk>',delete_conversion,name="delete-conversion"),
    path('edit_conversion/<int:pk>',edit_conversion,name="edit-conversion"),
    path('conversions/',conversion_list,name="conversion-list"),
]

accounts_site/urls.py
from django.contrib import admin
from django.urls import path,include
admin.site.site_url = '/auth/users' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('core.urls')),
]

core/urls.py
from django.urls import path
from core.views import *
app_name = 'core'
urlpatterns = [
    path('login/',login_page,name='login-page'),
    path('logout/',logout_user,name='logout'),
    path('user_login/',login_user,name='login-user'),
    path("users/", users_list,name = 'user-list'),
    path('save_user',save_user,name='save-user'),
    path('manage_user',manage_user,name='manage-user'),
    path('manage_user/<int:pk>',manage_user,name='manage-user-pk'),
    path('delete_user/<int:pk>',delete_user,name='delete-user'),
]

accounts/forms.py
from django import forms
from accounts import models
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm,PasswordChangeForm, UserChangeForm,PasswordResetForm
from django.contrib.auth import  get_user_model
from django.shortcuts import get_object_or_404
from django.db.models import Q  # Add this import
from django.db import IntegrityError

class SaveParty(forms.ModelForm):
    name = forms.CharField(max_length=255,required=True)
    address = forms.TextInput()
    pakistan_phone_validator = RegexValidator(
        regex=r'^(?:(?:\+92)|(?:0))(?:(?:3[0-9]{9})|(?:[1-9][0-9]{9}))$',
        message='Enter a valid phone number.',
    )
    phone_number = forms.CharField(
        label='Phone Number',
        validators=[pakistan_phone_validator],
        required=False
    )
    class Meta:
        model = models.Party
        fields = ['user', 'name', 'phone_number', 'address']


class SaveForm(forms.ModelForm):
    description = forms.TextInput()
    debit = forms.IntegerField(required=False)
    credit = forms.IntegerField(required=False)
    form = forms.IntegerField(required=False)
    party = forms.IntegerField(required=False)
    class Meta:
        model = models.Transaction
        fields = ['description','debit','credit','party','form']
    

accounts/views.py
import json
from django.views.decorators.csrf import csrf_exempt
from django.db import transaction
from django.db.models import Max
from django.core import serializers
from django.core.exceptions import PermissionDenied
from django.db.models import BooleanField, Case, When, Value,F
from django.views.generic import ListView
from django.shortcuts import render,redirect,get_object_or_404
from django.http import JsonResponse ,HttpResponse,HttpResponseForbidden
from django.contrib import messages 
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import update_session_auth_hash,logout,authenticate,login,get_user_model
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from decimal import Decimal
# Create your views here.
User = get_user_model()
def context_data(request):
    fullpath = request.get_full_path()
    abs_uri = request.build_absolute_uri()
    abs_uri = abs_uri.split(fullpath)[0]
    context = {
        'system_host': abs_uri,
        'page_name':'',
        'page_title':'',
        'system_name' : 'Accounts Managament System',
        'topbar':True,
        'footer':True,
    }
    return context

@login_required
def user_detail(request, pk=None):
    context = context_data(request)
    context['page'] = 'parties'
    context['page_title'] = 'Parties'
    options = []

    if pk:
        try:
            user = User.objects.get(pk=pk)
        except User.DoesNotExist:
            return HttpResponse(status=204)
        if (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None)==request.user or request.user.is_superuser:
            context['parties'] = Party.objects.select_related('user').filter(user = user)
            context['page_name'] = user
            context['user'] = user
            options.append(('product','Product')) if (request.user.has_perm('accounts.add_product') or request.user == user) else None
            options.append(('manage_transactions','Manage Transactions')) if (request.user.has_perm('accounts.can_manage_transactions') or request.user == user) else None
            options.append(('manage_s_p','Manage Sale/purchases')) if (request.user.has_perm('accounts.can_manage_s_p') or request.user == user) else None 
            options.append(('manage_conversion','Conversion Form'))  if (request.user.has_perm('accounts.view_conversion') or request.user == user) else None
        else:
            return redirect('accounts:user-detail')
    else:
        if (request.user.staffuser if hasattr(request.user, 'staffuser') else False) or request.user.is_superuser:
                return HttpResponse(status=204)
        user = User.objects.get(pk = request.user.pk)
        context['parties'] = Party.objects.filter(user = request.user)
        context['page_name'] = request.user
        context['user'] = request.user
        options.append(('product','Product')) if (request.user.has_perm('accounts.add_product') or request.user == user) else None
        options.append(('manage_transactions','Manage Transactions')) if (request.user.has_perm('accounts.can_manage_transactions') or request.user == user) else None
        options.append(('manage_s_p','Manage Sale/purchases')) if (request.user.has_perm('accounts.can_manage_s_p') or request.user == user) else None
        options.append(('manage_conversion','Conversion Form'))  if (request.user.has_perm('accounts.view_conversion') or request.user == user) else None
    context['options'] = options
    return render(request,'accounts/party.html',context)

@login_required
def manage_party(request,pk=None):
    context = context_data(request)
    context['page'] = 'manage_user'
    context['page_title'] = 'Manage User'

    if pk :
        try:
            party = Party.objects.select_related('user').get(pk=pk)
        except:
            HttpResponse(status=204)
        if party:

            if request.user.is_superuser or  (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None==request.user and request.user.has_perm('accounts.change_party')) or request.user == party.user :
                    context['party'] = party
            else:
                return HttpResponse("You are not Authorized to Edit This Party")
        else:
            return HttpResponse("The party is invalid")        
          
    else:
        user = User.objects.get(pk = request.GET.get('user_id'))

        if request.user.is_superuser or  (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None==request.user and  request.user.has_perm('accounts.add_party') or request.user == user ):
            context['user_id'] = user.pk
        else:
            HttpResponse("You are not Authorized to Add This Party")
    return render(request, 'accounts/manage_party.html', context)
            
@login_required
def save_party(request):
    resp = {'status': 'failed', 'msg': ''}

    if request.method == 'POST':
        post = request.POST
        party_id = post.get('id','')
        user_id = post.get('user','')
        if user_id:
            try:
                user = User.objects.get(pk=user_id)
            except:
                resp['msg'] = "User couldn't be found. Please Try Again After Refresh"
                return JsonResponse(resp)
            if party_id:
                try:
                    party = Party.objects.select_related('user').get(pk=party_id)
                except:
                    resp['msg'] = "Party coludn't be found. Please Try Again After Refresh"
                    return JsonResponse(resp)
                if request.user.is_superuser or party.user == request.user or (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None==request.user and request.user.has_perm('accounts.change_party')):
                    form = SaveParty(post, instance=party)
                else:
                    resp['msg'] = "You are not authorized to edit Party"
                    return JsonResponse(resp)
            else:
                if request.user.is_superuser or user == request.user  or  (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None==request.user and request.user.has_perm('accounts.add_party')):
                    form = SaveParty(post)
                else:
                    resp['msg'] = "You are not authorized to Add Party"
                    return JsonResponse(resp)
                
        if form.is_valid():
            form.save()

            if party_id == '':
                messages.success(request, "Party has been saved successfully.")
            else:
                messages.success(request, "Party has been updated successfully.")
            resp['status'] = 'success'
        else:
            for field in form:
                for error in field.errors:
                    if resp['msg'] != '':
                        resp['msg'] += '<br/>'
                    resp['msg'] += f'[{field.name}] {error}'

    else:
        resp['msg'] = "There's no data sent in the request"
    return JsonResponse(resp)


@login_required
def delete_party(request, pk=None):
    resp = {
        'status': 'failed',
        'msg': ''
    }

    if pk:
        party = Party.objects.select_related('user').filter(pk = pk)
        if party:
            if request.user.is_superuser or party[0].user == request.user  or (party.user.assigned_staff.user if hasattr(party.user.assigned_staff, 'user') else None==request.user and request.user.has_perm('accounts.delete_party')):
                if party[0].delete_flag == 0:
                    try:
                        party.update(delete_flag=1)
                        messages.success(request, "Party has been moved to recycle bin successfully.")
                        resp['status'] = 'success'
                    except:
                        resp['msg'] = "Deleting User Failed."
                else:
                    party.delete()
                    messages.success(request,"Party has been deleted successfully.")
                    resp['status'] = 'success'
            else:
                resp['msg'] = "You are not authorized to delete party."
                return JsonResponse(resp)
        else:
            resp['msg'] = "Party couldn't be found. Please Try agin after refresh"
            return JsonResponse(resp)
    
    else:
        resp['msg'] = "There's no data sent in the request"

    return HttpResponse(json.dumps(resp),content_type="application/json")

@login_required
def manage_transaction(request, pk=None):
    context = context_data(request)
    context['page'] = 'manage_transaction'
    context['page_title'] = 'Manage Transaction'
    user_id = request.GET.get('user_id', '')
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        return HttpResponse("The user Couldn't be found. Please Refresh and Try again")

    if pk is None:
        # Adding a new transaction
        if request.user.is_superuser or request.user == user or  (user.assigned_staff.user if hasattr(user.assigned_staff,'user') else False == request.user and request.user.has_perm('accounts.can_manage_transactions')):
            
            context['user_id'] = user.id
            context['parties'] = Party.objects.filter(user=user, delete_flag=0)
        else:
            return HttpResponse("You are not allowed to manage Transactions. Please contact admin for further queries")
    else:
        resp = {
            'msg':"",
            'status':'failed'
        }
        # Editing an existing transaction
        if (request.user.is_superuser or 
            user == request.user or
            ((request.user.has_perm('accounts.change_transaction')  and
            user.assigned_staff.user if hasattr(user.assigned_staff,'user') else False == request.user))):
            try:
                transaction = Transaction.objects.get(pk=pk)
            except:

templates/accounts/manage_party.html
{% load static %}
<body>
<div class="container-fluid">
    <form action="" id="party-form">
    {% if party.user.id %}
        <input type="hidden" name="user" value="{{party.user.id}}">
    {% else %}
        <input type="hidden" name="user" value="{{user_id}}">
    {% endif %}
        <input type="hidden" name="id" value="{{party.id}}">
        <div class="mb-3">
            <label for="name" class="control-label">Name</label>
            <input type="text" id="name" name="name" class="form-control form-control-sm rounded-0" value="{{party.name}}" required>
        </div>
        <div class="form-group mb-3">
            <label for="phone_number" class="control-label">Phone Number</label>
            <input type="text" class="form-control rounded-0" name="phone_number" id="phone_number" value="{% if form.data.phone_number %}{{ form.data.phone_number }}{% else %}{{ party.phone_number }}{% endif %}" >
        </div>
        <div class="mb-3">
            <label for="address" class="control-label">Address</label>
            <textarea rows="3" id="address" name="address" class="form-control form-control-sm rounded-0" >{{party.address}}</textarea>        </div>
        
    </form>
</div>
</body>
<script>
    $(function() {
        $('#party-form').submit(function(e) {
            e.preventDefault();
            var _this = $(this)
            $('.err-msg').remove();
            var el = $('<div>')
            el.addClass("alert alert-danger err-msg")
            el.hide()
            if (_this[0].checkValidity() == false) {
                _this[0].reportValidity();
                return false;
            }
            start_loader();
            $.ajax({
                headers: {
                    "X-CSRFToken": '{{csrf_token}}'
                },
                url: "{% url 'accounts:save-party' %}",
                data: new FormData($(this)[0]),
                cache: false,
                contentType: false,
                processData: false,
                method: 'POST',
                type: 'POST',
                dataType: 'json',
                error: err => {
                    console.log(err)
                    alert("An error occured", 'error');
                    end_loader();
                },
                success: function(resp) {
                    if (typeof resp == 'object' && resp.status == 'success') {
                        location.reload()
                    } else if (resp.status == 'failed' && !!resp.msg) {
                        el.text(resp.msg)
                    } else {
                        el.text("An error occured", 'error');
                        end_loader();
                        console.log(resp)
                    }
                    _this.prepend(el)
                    el.show('slow')
                    $("html, body, .modal").scrollTop(0);
                    end_loader()
                }
            })
        })
    })
</script>

templates/accounts/party.html
{% extends 'base.html' %} {% load static %} {% block pageContent %} {% load customfilter %}
<style>
    .al-logo {
        height: 3em;
        width: 3em;
        object-fit: scale-down;
        object-position: center center;
    }
    
</style>
<section class="py-4">
    <div class="container"> 
        <h3 class="fw-bolder text-center">List of Parties</h3>
        <center>
            <hr class="bg-primary opacity-100" style="height:3px" width="5%">
        </center>
        <div class="card rounded-0 shadow">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="text-end mb-3">
                        <button class="btn rounded-0" type="button" id="create_new"><i class="fa fa-plus"></i> Add New Party</button>
                    </div>
                    <div class="form-group">
                    <label for="filterCheckbox">Filter Records according to:</label>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="check-debit">
                        <label class="form-check-label" for="checkbox1">
                        Debit
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" id="check-credit">
                        <label class="form-check-label" for="checkbox2">
                        Credit
                        </label>
                    </div>
                    </div>

                    <table class="display cell-border" class="table table-bordered table-striped" style="width:100%" id="party-tbl">
                        <thead>
                            <tr>
                                <th >#</th>
                                <th >Name</th>
                                <th >Address</th>
                                <th >Phone_number</th>
                                <th >Balance</th>
                                <th >Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for party in parties %}
                            <tr>
 
                                <td>{{ forloop.counter }}</td>
                                <td>{{ party.name}}</td>
                                <td>{{ party.address | check_value}}</td>
                                <td>
                                    <p class="m-0 truncate-1">{{ party.phone_number | check_value }}</p>
                                </td>
                                <td>
                                    {% with balance=party.balance %}
                                        {% if balance > 0 %}
                                            <p class="m-0 truncate-1 text-success">{{ balance }}(+)</p>
                                        {% elif balance < 0 %}
                                            <p class="m-0 truncate-1 text-danger">{{ balance | abs }}(-)</p>
                                        {% else %}
                                            <p class="m-0 truncate-1">{{ balance }}</p>
                                        {% endif %}
                                    {% endwith %}
                                </td>

                                <td>
                                
                                    <div class="dropdown">
                                        <button class="btn btn-light btn-sm rounded-0 border dropdown-toggle" type="button" id="abtn{{cat.pk}}" data-bs-toggle="dropdown" aria-expanded="false">
                                          Action
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="abtn{{party.pk}}">
                                            <li>
                                            <a class="dropdown-item view-data-trans" href="{% url 'accounts:view-transactions' party.pk %}"><i class="fa fa-eye text-dark"></i>View Transactions</a>
                                            </li>
                                            <li><a class="dropdown-item edit-data" href="javascript:void(0)" data-url="{% url 'accounts:manage-party-pk' party.pk %}"><i class="fa fa-edit text-primary"></i> Edit</a></li>
                                            <li><a class="dropdown-item delete-data" href="javascript:void(0)" data-url="{% url 'accounts:delete-party' party.pk %}"><i class="fa fa-trash text-danger"></i> Delete</a></li>
                                        </ul>
                                    </div>
                                
                                </td>
                 
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table> 
                </div>
            </div>
        </div>
    </div> 
</section>
{% endblock pageContent %} {% block ScriptBlock %}
<script>
    $(function() {
        $('#check-debit').on('change',function(){
            if ($(this).prop('checked')){
                dataTable.search("(+)").draw()
                 $('#check-credit').prop('checked',false)

            }else{
                dataTable.search("").draw()
            }
        })
        $('#check-credit').on('change',function(){
            if ($(this).prop('checked')){
                dataTable.search("(-)").draw()
                 $('#check-debit').prop('checked',false)
            }else{
                dataTable.search("").draw()
            }
        })
        $('#new_form_product').click(function(){
            window.location.href = "{% url 'accounts:products-pk' pk=user.id %}"
        })
        $('#create_new').click(function() {
            $.ajax({
            url: "{% url 'accounts:manage-party'  %}",
            method: 'GET',
            data: {
                'user_id': {{user.id}},
            },
            error: err =>{
                    alert("An error occured")
                },
            success: function(resp){
                if(resp){
                    $('#uni_modal .modal-title').html("Add New Party")
                    $('#uni_modal .modal-body').html(resp)
                    
                    $('#uni_modal').modal({
                        backdrop:'static',
                        keyboard:false,
                        focus:true
                    })
                    $("#uni_modal").modal('show')
                    end_loader()
                }
            }
});
             
        })
            // Attach click event to the view-data link

        
        $('.edit-data').click(function() {
            uni_modal("<i class='fa fa-edit'></i> Edit Party Details", $(this).attr('data-url'))
        })
        $('.view_image').click(function() {
            var img = $(this).attr('data-img-url')
            $('#viewer_modal #img-viewer-field').attr('src', img)
            $('#viewer_modal').modal('show')
        })
        $('.delete-data').click(function() {
            _conf("Are you sure to delete this party?", 'delete_party', ["'" + $(this).attr('data-url') + "'"])
        })
        $('#party-tbl').find('td, th').addClass('px-2 py-1 align-middle')
        var dataTable = $('#party-tbl').DataTable({
            layout: {
                    topStart: {
                        buttons: [
                        {% comment %} {
                            extend: 'print',
                            title: '',
                            autoPrint: true,
                            customize: function (win) {
                                $(win.document.body).find('th:last-child').text('Received');
                                $(win.document.body).find('td:last-child').empty();
                            }
                        }, {% endcomment %}
                        {
                                extend: 'pdfHtml5',
                                title:"",
                                exportOptions: {
                                    columns: [ 1, 2, 3,4 ],
                             

                                },
                                customize: function (doc) {
                                    doc.styles['table'] = {alignment:'center'};
                                    doc.pageMargins = [20,0,20,30];
                                    doc.content[0].table.widths = [  '30%', '25%', '18%','15%','12%'];
                                    processDoc(doc);
                                   addExtraColumn(doc);
                                    doc.content[0].layout = 'lightHorizontalLines'  
                                }
                            }
                        ]  
                }
            }, 
            responsive: {
                details: {
                    type: 'column',
                    target: 'tr'
                }
            },
            columnDefs: [
                {
                    orderable: false,
                    targets: [1,2,3,4,5]
                },
                { "width": "120px", "targets": 3 }, // Set width for the first column
                { "width": "90px", "targets": 4 },   // Set width for the third column
                { "width": "40px", "targets": 5 },
                { responsivePriority: 1, targets: 1 },
                { responsivePriority: 2, targets: -1 },
                { responsivePriority: 3, targets: 4 },
            ],
            order: [[0, 'asc']],
            lengthMenu: [
                [25, 50, 100, -1],
                [25, 50, 100, "All"]
            ],
        })
        var hideColumnIndex = 0;
        var column = dataTable.column(hideColumnIndex);
        column.visible(false);

})

    function delete_party(url) {

        var _this = $('#confirm_modal .modal-body')
        $('.err-msg').remove();
        var el = $('<div>')
        el.addClass("alert alert-danger err-msg")
        el.hide()
        start_loader()
        $.ajax({
            headers: {
                "X-CSRFToken": "{{csrf_token}}"
            },
            url: url,
            dataType: 'JSON',
            error: err => {
                console.log(err)
                alert("an error occurred.")
                end_loader()
            },
            success: function(resp) {
                if (resp.status == 'success') {
                    location.reload()
                } else if (!!resp.msg) {
                    el.html(resp.msg)
                    _this.prepend(el)
                    el.show()
                } else {
                    el.html("An error occurred")
                    _this.prepend(el)
                    el.show()
                }
                end_loader()
            }

        })
    }
    function processDoc(doc) {
    pdfMake.fonts = {
      Roboto: {
        normal: 'Roboto-Regular.ttf',
        bold: 'Roboto-Medium.ttf',
        italics: 'Roboto-Italic.ttf',
        bolditalics: 'Roboto-MediumItalic.ttf'
      },
      arial: {
        normal: 'arial.ttf',
        bold: 'arial.ttf',
        italics: 'arial.ttf',
        bolditalics: 'arial.ttf'
      },
      noto:{
        normal: 'noto.ttf',
        bold: 'noto.ttf',
        italics: 'noto.ttf',
        bolditalics: 'noto.ttf'
      }
    };
    // modify the PDF to use a different default font:
    doc.defaultStyle.font = "noto";
    var i = 1;
    }
    function addExtraColumn(pdf) {
    pdf.content[0].table.body.forEach(function(row, idx) { 
      let newCell = structuredClone(row[0]);
      newCell.text = idx === 0 ? "Received" : "";
      row.push( newCell );
    })
  };
</script>
{% endblock ScriptBlock %}