accounts/urls.py
from django.urls import path
from accounts.views import *

app_name='accounts'
urlpatterns = [
    path('',user_detail,name='user-detail-pk'),
    path("auth/users/<int:pk>", user_detail,name = 'user-detail-pk'),
    path("parties", user_detail,name = 'user-detail'),
    path('manage_party',manage_party,name='manage-party'),
    path('save_party',save_party,name='save-party'),
    path('manage_party/<int:pk>',manage_party,name='manage-party-pk'),
    path('delete_party/<int:pk>',delete_party,name='delete-party'),
    path('manage_transaction/<int:pk>/',manage_transaction,name='manage-transaction'),
    path('manage_transaction/',manage_transaction,name='manage-transaction'),
    path('save_transactions/', save_transaction, name='save-transaction'),
    path('transactions_list/',transaction_list, name='transaction_list'),
    path('delete_transaction/<int:pk>', delete_transaction, name='delete-transaction'),
    path('view_transactions/<int:pk>', view_transactions, name='view-transactions'),
    path('manage_sales_purchase',manage_sales_purchases,name='manage-sales-purchase'),
    path('manage_sales_purchase/<int:pk>/',manage_sales_purchases,name='manage-sales-purchase'),
    path('save_trade',save_trade,name="save-trade"),
    path('sales_list/',sales_list, name='sales_list'),
    path('purchases_list/',purchases_list, name='purchases_list'),
    path('products/',products,name="products"),
    path('products/<int:pk>',products,name="products-pk"),
    path('manage_products/',manage_products,name="manage-products"),
    path('manage_products/<int:pk>',manage_products,name="manage-products-pk"),
    path('save_products/',save_product,name="save-product"),
    path('delete_product/<int:pk>',delete_product,name="delete-product"),
    path('print/<int:pk>',print_veiw,name="print-view-pk"),
    path('manage_conversion/',conversion,name="conversion"),
    path('save_conversion/',save_conversion,name="save-conversion"),
    path('identifier/',check_identifier,name="check-id"),
    path('delete_conversion/<int:pk>',delete_conversion,name="delete-conversion"),
    path('edit_conversion/<int:pk>',edit_conversion,name="edit-conversion"),
    path('conversions/',conversion_list,name="conversion-list"),
]

accounts_site/urls.py
from django.contrib import admin
from django.urls import path,include
admin.site.site_url = '/auth/users' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('core.urls')),
]

core/urls.py
from django.urls import path
from core.views import *
app_name = 'core'
urlpatterns = [
    path('login/',login_page,name='login-page'),
    path('logout/',logout_user,name='logout'),
    path('user_login/',login_user,name='login-user'),
    path("users/", users_list,name = 'user-list'),
    path('save_user',save_user,name='save-user'),
    path('manage_user',manage_user,name='manage-user'),
    path('manage_user/<int:pk>',manage_user,name='manage-user-pk'),
    path('delete_user/<int:pk>',delete_user,name='delete-user'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(unique=True,max_length=15)
    question = models.TextField(blank=True,null=True)
    answer = models.TextField(blank=True,null=True)
    assigned_staff = models.ForeignKey('StaffUser',on_delete=models.SET_NULL,blank=True,null=True,related_name="assigned_staff")
    class Meta:
        permissions = (
            ("can_assign_staff","Can Assign Staff to Users"),
        )


class StaffUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL,null=True)
    def __str__(self) -> str:
        return f"{self.user}"

core/forms.py
from django import forms
from core.models import StaffUser
from django.core.validators import RegexValidator
from django.contrib.auth.forms import *
from django.contrib.auth import get_user_model
User = get_user_model()
class SaveUser(UserCreationForm):
    pakistan_phone_validator = RegexValidator(
        regex=r'^(?:(?:\+92)|(?:0))(?:(?:3[0-9]{9})|(?:[1-9][0-9]{9}))$',
        message='Enter a valid phone number.',
    )
    phone_number = forms.CharField(
        label='Phone Number',
        validators=[pakistan_phone_validator],
        required=True
    )
    username = forms.CharField(max_length=250,help_text="The Username field is required.")
    email = forms.EmailField(max_length=250,required=False)
    first_name = forms.CharField(max_length=250,required=False)
    last_name = forms.CharField(max_length=250,required=False)
    question = forms.CharField(max_length=255,required=False)
    answer = forms.CharField(max_length=255,required=False)
    assigned_staff = forms.CharField(max_length=255,required=False,empty_value=None)
    password1 = forms.CharField(max_length=250)
    password2 = forms.CharField(max_length=250)

    class Meta:
        model = User
        fields = ( 'username','phone_number','password1', 'password2','email','assigned_staff','first_name', 'last_name','question','answer')

class UpdateUser(UserChangeForm):
    pakistan_phone_validator = RegexValidator(
        regex=r'^(?:(?:\+92)|(?:0))(?:(?:3[0-9]{9})|(?:[1-9][0-9]{9}))$',
        message='Enter a valid phone number.',
    )
    phone_number = forms.CharField(
        label='Phone Number',
        validators=[pakistan_phone_validator],
        required=True
    )
    username = forms.CharField(max_length=250)
    email = forms.EmailField(max_length=250,required=False)
    first_name = forms.CharField(max_length=250,required=False)
    last_name = forms.CharField(max_length=250,required=False)
    question = forms.CharField(max_length=255,required=False)
    assigned_staff = forms.CharField(max_length=255,required=False,empty_value=None)
    answer = forms.CharField(max_length=255,required=False)
    
    class Meta:
        model = User
        fields = ('username','assigned_staff','email','phone_number','first_name', 'last_name','question','answer')

class SaveStaffUser(forms.ModelForm):
    class Meta:
        model = StaffUser
        fields = ('user',)

core/views.py
from django.shortcuts import render

# Create your views here.
import json
from django.db.models import BooleanField, Case, When, Value
from django.views.generic import ListView
from django.shortcuts import render,redirect,get_object_or_404
from django.http import JsonResponse ,HttpResponse,HttpResponseForbidden
from django.contrib import messages 
from django.contrib.auth import update_session_auth_hash,logout,authenticate,login,get_user_model
from django.contrib.auth.decorators import login_required
from .models import StaffUser
from .forms import *
# Create your views here.
User = get_user_model()
def context_data(request):
    fullpath = request.get_full_path()
    abs_uri = request.build_absolute_uri()
    abs_uri = abs_uri.split(fullpath)[0]
    context = {
        'system_host': abs_uri,
        'page_name':'',
        'page_title':'',
        'system_name' : 'Accounts Managament System',
        'topbar':True,
        'footer':True,
    }
    return context

def login_page(request):
    context = context_data(request)
    context['topbar'] = False
    context['footer'] = False
    context['page_name'] = 'login'
    context['page_title'] = 'Login'
    return render(request,'core/login.html',context)

def logout_user(request):
    logout(request)
    return redirect("core:login-page")

def login_user(request):
    logout(request)
    resp = {
        "status":'failed',
        'msg':''
    }
    username = ''
    password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username = username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                resp['status'] = 'success'
            else:
                resp['msg'] = "Incorrect username or password"
        else:
            resp['msg'] = "Incorrect username or password"
    return HttpResponse(json.dumps(resp),content_type = 'application/json')

@login_required
def users_list(request):
    context = context_data(request)
    context['page'] = 'users'
    context['page_title'] = 'Users'
    context['page_name'] = context['system_name']
    if (request.user.staffuser if hasattr(request.user, 'staffuser') else False) or request.user.is_superuser:
        context['staff_users'] = StaffUser.objects.all()
        if request.user.is_superuser:
            users = User.objects.exclude(id = request.user.id)
        else:
            users = User.objects.filter(assigned_staff__user = request.user)
    else:
        return redirect('accounts:user-detail')
        
    context['users'] = users
    return render(request,'core/user_list.html',context)

@login_required
def save_user(request):
    resp = {
        'status':'failed',
        'msg':''
    }
    
    if request.method == 'POST':
        post = request.POST
        user_id = post.get('id','')
        staff = post.get('staff','')
        is_staff = post.get('is_staff','')
        if user_id:
            user = get_object_or_404(User,id=user_id)
            if request.user.is_superuser or (request.user.staffuser if hasattr(request.user, 'staffuser') else False) and (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None)==request.user:
                
                    form = UpdateUser(post,instance=user)
            else:
                resp['msg'] = "You are not authorized to edit Users"
                return JsonResponse(resp)
        else:
            if request.user.is_superuser or  (request.user.staffuser if hasattr(request.user, 'staffuser') else False):
                    form = SaveUser(post)
            else:
                resp['msg'] = "You are not authorized to Add Users"
                return JsonResponse(resp)

        if form.is_valid():
            save_instance = form.save(commit=False)
            try:
                assigned_staff = StaffUser.objects.get(user__username = staff)
            except:
                assigned_staff = None
            if request.user.is_superuser:
                if user_id:
                    if is_staff == 'on' and not staff:
                        staff_user,created = StaffUser.objects.get_or_create(user=user)
                        assigned_staff = None
                        
                    else:
                        StaffUser.objects.filter(user=user).delete()
                    messages.success(request, "User has been updated successfully.")
                else:
                    if assigned_staff and not is_staff:
                        assigned_staff = assigned_staff
                    elif not is_staff:
                        assigned_staff = None
                    else:
                        save_instance.save()
                        staffuser , _ = StaffUser.objects.get_or_create(user=save_instance)
                        resp['status']  = 'success'
                        return JsonResponse(resp)

            else:
                staff_instance = get_object_or_404(StaffUser,user=request.user)
                assigned_staff = staff_instance

                
            save_instance.assigned_staff = assigned_staff
            save_instance.save()
            resp['status']  = 'success'
        else:
            for field in form:
                for error in field.errors:
                    resp['msg'] += f"[{field.name}] {error} <br/>"
    
    else:
        resp['msg'] = "There's no data sent on the request"

    return JsonResponse(resp)

@login_required
def manage_user(request,pk=None):
    context = context_data(request)
    context['page'] = 'manage_user'
    context['page_title'] = 'Manage User'
    if pk is None:
        if request.user.is_superuser or  (request.user.staffuser if hasattr(request.user, 'staffuser') else False):
            context['user'] = {}
            if request.user.is_superuser:
                context['staff_users'] = StaffUser.objects.only('user')
        else:
            return HttpResponse("You are not authorized to add Users")
        
    else:
        
        if request.user.is_superuser or request.user.has_perm('core.change_user') and (request.user.staffuser if hasattr(request.user, 'staffuser') else False):
            user = get_object_or_404(User,pk=pk)
            if (user.assigned_staff.user if hasattr(user.assigned_staff, 'user') else None)==request.user or request.user.is_superuser:
                if request.user.has_perm('core.can_assign_staff_user'):
                    staff_users = StaffUser.objects.all()
                    context['staff_users'] = staff_users
                    
                    if  (user.staffuser if hasattr(user, 'staffuser') else False):
                        context['is_staff'] = True
                    else:
                        context['is_staff'] = False
                context['user'] = user
            else:
                return HttpResponseForbidden()
        else:
            return HttpResponseForbidden()
        
    return render(request, 'core/manage_user.html', context)

@login_required
def delete_user(request, pk=None):
    resp = {
        'status': 'failed',
        'msg': ''
    }

    if pk:
        if request.user.is_superuser or (request.user.staffuser if hasattr(request.user, 'staffuser') else False):
            user = get_object_or_404(User,pk=pk)
            if user.is_active:
                try:
                    user.is_active = False
                    user.save()
                    messages.success(request, "User has been deactivated successfully")
                    resp['status'] = 'success'
                except Exception:
                    resp['msg'] = 'Deactivatibg User Failed'
                    
            else:
                try:
                    user.delete()
                    messages.success(request,"User has been deleted successfully")
                    resp['status'] = "success"
                except Exception:
                    resp['msg'] = 'Deleting User Failed'
        else:
            resp['msg'] = "You are not authorized to delete Users"
        
        return HttpResponse(json.dumps(resp),content_type="application/json")
    
    else:
        resp['msg'] = "There's no data sent in the request"

    return JsonResponse(resp)

templates/core/login.html
{% extends 'base.html' %}
{% load static %}

{% block pageContent %}
<style>
    body {
        background-image: url('{% static "assets/default/img/wallpaper.jpg" %}');
        background-repeat: no-repeat;
        background-size: cover;
        margin: 0;
        padding: 0;
        font-family: 'Arial', sans-serif;
    }

    main {
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: auto;
    }


    #logo-img {
        height: 7em;
        width: 7em;
        object-fit: cover;
        object-position: center center;
        border: 2px solid #fff;
        border-radius: 50%;
        animation: pulse 2s infinite; /* Add a subtle pulse animation */
    }

    @keyframes pulse {
        0% {
            transform: scale(1);
        }
        50% {
            transform: scale(1.1);
        }
        100% {
            transform: scale(1);
        }
    }

    #page-title {
        font-size: 3em;
        color: #f7f7f7;
        font-family: 'Cursive', sans-serif;
        text-shadow: 2px 2px 12px #b7652a;
    }

    .card {
        width: 100%;
        max-width: 400px;
        margin: 20px auto;
        border: none;
        border-radius: 15px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
        overflow: hidden;
        transition: transform 0.3s ease; /* Add a smooth transition on hover */
    }

    .card:hover {
        transform: scale(1.05);
    }

    .card-header {
        background-color: #878787;
        color: #fff;
        text-align: center;
        padding: 15px;
        border-top-left-radius: 15px;
        border-top-right-radius: 15px;
    }

    .card-title {
        margin-bottom: 0;
    }

    .card-body {
        padding: 20px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .form-control {
        border-radius: 8px;
        border: 1px solid #ced4da;
        transition: border-color 0.3s ease;
    }

    .form-control:focus {
        border-color: #878787;
        box-shadow: 0 0 0 0.2rem rgba(0, 123, 255, 0.25);
    }

    .btn-primary {
        border-radius: 8px;
        background-color: #878787;
        border: 1px solid #878787;
        transition: background-color 0.3s ease;
    }

    .btn-primary:hover {
        background-color: #615c5c;
        border-color: #615c5c;
    }

    .not-registered {
        text-align: center;
        margin-top: 20px;
    }

    .signup-link {
        color: #007bff;
        cursor: pointer;
        text-decoration: underline;
        transition: color 0.3s ease;
    }

    .signup-link:hover {
        color: #0056b3;
    }
</style>

<div class="d-flex flex-column w-100 justify-content-center align-items-center">
    <div class="text-center">
        <img src="{% static 'assets/default/img/logo.jpg' %}" alt="Logo" class="bg-gradient bg-dark bg-opacity-75 rounded-circle padding-0 border" id="logo-img">
    </div>
    <div class="col-lg-6 col-md-8 col-sm-12 col-xs-12 py-5 mb-3">
        <h2 class="text-center fw-bolder" id="page-title">{{system_name}}</h2>
    </div>
    <div class="col-lg-8 col-md-10 col-sm-12 col-xs-12 pt-3">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title"><b>Login</b></h4>
            </div>
            <div class="card-body">
                <form id="login-user" action="" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="control-label">Username</label>
                        <input type="text" class="form-control" autofocus name="username" id="username" required="required">
                    </div>
                    <div class="form-group">
                        <label for="password" class="control-label">Password</label>
                        <input type="password" class="form-control" autofocus name="password" id="password" required="required">
                    </div>
                    <div class="form-group">
                        <div class="d-flex justify-content-center">
                            <button class="btn btn-primary">
                                Login
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock pageContent %}


{% block ScriptBlock %}
<script>
     $(function () {
        $('#login-user').submit(function (e) {
            e.preventDefault();
            var _this = $(this)
            $('.err-msg').remove();
            var el = $('<div>')
            el.addClass("alert alert-danger err-msg")
            el.hide()
            if (_this[0].checkValidity() == false) {
                _this[0].reportValidity();
                return false;
            }
            start_loader();
            $.ajax({
                headers: {
                    "X-CSRFToken": '{{csrf_token}}'
                },
                url: "{% url 'core:login-user' %}",
                data: new FormData($(this)[0]),
                cache: false,
                contentType: false,
                processData: false,
                method: 'POST',
                type: 'POST',
                dataType: 'json',
                error: err => {
                    console.log(err)
                    alert("An error occurred", 'error');
                    end_loader();
                },
                success: function (resp) {
                    if (typeof resp == 'object' && resp.status == 'success') {
                        el.removeClass("alert alert-danger err-msg")
                        location.href = "{% url 'core:user-list' %}"
                    } else if (resp.status == 'failed' && !!resp.msg) {
                        el.text(resp.msg)
                    } else {
                        el.text("An error occurred", 'error');
                        end_loader();
                        console.error(resp)
                    }
                    _this.prepend(el)
                    el.show('slow')
                    $("html, body, .modal").scrollTop(0);
                    end_loader()
                }
            })
        })
    }) 
</script>
{% endblock ScriptBlock %}

templates/core/user_list.html
{% extends 'base.html' %} {% load static %} {% block pageContent %}
<section class="py-4">
    <div class="container">
        <h3 class="fw-bolder text-center">List of Clients</h3>
        <center>
            <hr class="bg-primary opacity-100" style="height:3px" width="5%">
           
        </center>
        <div class="card rounded-0 shadow">
            <div class="card-body">
                <div class="container-fluid">
                    <div class="text-end mb-3">
                        <button class="btn btn-sm btn" type="button" id="create_new"><i class="fa fa-plus"></i> Add New Client</button>
                    </div>
                    <table class="table table-bordered table-striped" id="user-tbl">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th class="text-center">Username</th>
                                <th class="text-center">Phone_number</th>
                                {% if request.user.is_superuser %}
                                <th class="text-center">Staff Assigned</th>
                                <th class="text-center">Is_Staff</th>
                                {% endif %}
                                <th class="text-center">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for user in users %}
                            
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td>
                                    {% if user.staffuser %}
                                    <a style="text-decoration:none; color: black;"  >{{ user.username}}</a>
                                    {% else %}
                                    <a style="text-decoration:none; color: black;" href="{% url 'accounts:user-detail-pk' user.pk %}" >{{ user.username}}</a>
                                    {% endif %}
                                </td>
                                <td>{{ user.phone_number }}</td>
                                {% if request.user.is_superuser %}
                                <td>{{ user.assigned_staff }}</td>
                                {% if user.staffuser %}
                                <td><input id="userlist_checkbox" type="checkbox" checked  ></td>
                                {% else %}
                                <td><input id="userlist_checkbox" type="checkbox"   ></td>
                                {% endif %}
                                {% endif %}
                                <td class="text-center">
                                    <div class="dropdown">
                                        <button class="btn btn-light btn-sm rounded-0 border dropdown-toggle" type="button" id="abtn{{user.pk}}" data-bs-toggle="dropdown" aria-expanded="false">
                                          Action
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="abtn{{user.pk}}">
                                            <li><a class="dropdown-item edit-data" href="javascript:void(0)" data-url="{% url 'core:manage-user-pk' user.pk %}"><i class="fa fa-edit text-primary"></i> Edit</a></li>
                                            <li><a class="dropdown-item delete-data" href="javascript:void(0)"  data-url="{% url 'core:delete-user' user.pk %}"><i class="fa fa-trash text-danger"></i> Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock pageContent %} {% block ScriptBlock %}
<script>
    
    $(function() {
         $('#create_new').click(function() {
            uni_modal("<i class='fa fa-plus'></i> Add New User", "{% url 'core:manage-user' %}")
        })
        
        $('.edit-data').click(function() {
            uni_modal("<i class='fa fa-edit'></i> Edit User Details", $(this).attr('data-url'))
        })
        $('.delete-data').click(function() {
            _conf("Are you sure to delete this User?", 'delete_user', ["'" + $(this).attr('data-url') + "'"])
        })
        
        $('#user-tbl').DataTable({
            responsive: {
                    details: {
                        type: 'column',
                        target: 0
                    }
                },
            columnDefs: [
                { orderable:false, targets: [-1] },
                { responsivePriority: 1, targets: -1 },
                { responsivePriority: 2, targets: 1 },
                { responsivePriority: 3, targets: 0 },
                {"className": "dt-center", "targets": [4]},
                {"className": "dt-left", "targets": [2]}
            ],
            lengthMenu: [
                [25, 50, 100, -1],
                [25, 50, 100, "All"]
            ],
        })
    })

    function delete_user(url) {
        var _this = $('#confirm_modal .modal-body')
        $('.err-msg').remove();
        var el = $('<div>')
        el.addClass("alert alert-danger err-msg")
        el.hide()
        start_loader()
        $.ajax({
            headers: {
                "X-CSRFToken": "{{csrf_token}}"
            },
            url: url,
            dataType: 'JSON',
            error: err => {
                console.log(err)
                alert("an error occurred.")
                end_loader()
            },
            success: function(resp) {
                if (resp.status == 'success') {
                    location.reload()
                } else if (!!resp.msg) {
                    el.html(resp.msg)
                    _this.prepend(el)
                    el.show()
                } else {
                    el.html("An error occurred")
                    _this.prepend(el)
                    el.show()
                }
                end_loader()
            }

        })
    }
</script> 
{% endblock ScriptBlock %}