accounts/urls.py
from django.urls import path
from accounts.views import *

app_name='accounts'
urlpatterns = [
    path('',user_detail,name='user-detail-pk'),
    path("auth/users/<int:pk>", user_detail,name = 'user-detail-pk'),
    path("parties", user_detail,name = 'user-detail'),
    path('manage_party',manage_party,name='manage-party'),
    path('save_party',save_party,name='save-party'),
    path('manage_party/<int:pk>',manage_party,name='manage-party-pk'),
    path('delete_party/<int:pk>',delete_party,name='delete-party'),
    path('manage_transaction/<int:pk>/',manage_transaction,name='manage-transaction'),
    path('manage_transaction/',manage_transaction,name='manage-transaction'),
    path('save_transactions/', save_transaction, name='save-transaction'),
    path('transactions_list/',transaction_list, name='transaction_list'),
    path('delete_transaction/<int:pk>', delete_transaction, name='delete-transaction'),
    path('view_transactions/<int:pk>', view_transactions, name='view-transactions'),
    path('manage_sales_purchase',manage_sales_purchases,name='manage-sales-purchase'),
    path('manage_sales_purchase/<int:pk>/',manage_sales_purchases,name='manage-sales-purchase'),
    path('save_trade',save_trade,name="save-trade"),
    path('sales_list/',sales_list, name='sales_list'),
    path('purchases_list/',purchases_list, name='purchases_list'),
    path('products/',products,name="products"),
    path('products/<int:pk>',products,name="products-pk"),
    path('manage_products/',manage_products,name="manage-products"),
    path('manage_products/<int:pk>',manage_products,name="manage-products-pk"),
    path('save_products/',save_product,name="save-product"),
    path('delete_product/<int:pk>',delete_product,name="delete-product"),
    path('print/<int:pk>',print_veiw,name="print-view-pk"),
    path('manage_conversion/',conversion,name="conversion"),
    path('save_conversion/',save_conversion,name="save-conversion"),
    path('identifier/',check_identifier,name="check-id"),
    path('delete_conversion/<int:pk>',delete_conversion,name="delete-conversion"),
    path('edit_conversion/<int:pk>',edit_conversion,name="edit-conversion"),
    path('conversions/',conversion_list,name="conversion-list"),
]

accounts_site/urls.py
from django.contrib import admin
from django.urls import path,include
admin.site.site_url = '/auth/users' 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('auth/', include('core.urls')),
]

core/urls.py
from django.urls import path
from core.views import *
app_name = 'core'
urlpatterns = [
    path('login/',login_page,name='login-page'),
    path('logout/',logout_user,name='logout'),
    path('user_login/',login_user,name='login-user'),
    path("users/", users_list,name = 'user-list'),
    path('save_user',save_user,name='save-user'),
    path('manage_user',manage_user,name='manage-user'),
    path('manage_user/<int:pk>',manage_user,name='manage-user-pk'),
    path('delete_user/<int:pk>',delete_user,name='delete-user'),
]

templates/405.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>405 Method Not Allowed</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }
        .container {
            max-width: 800px;
            margin: 50px auto;
            text-align: center;
        }
        h1 {
            color: #ff0000;
        }
        p {
            color: #666;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>405 Method Not Allowed</h1>
        <p>The requested method is not allowed for this resource.</p>
    </div>
</body>
</html>

templates/base.html
{% load static %} 
{% load customfilter %}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% if page_title %}
    <title>{{page_title}} | {{system_name}}</title>
    {% else %}
    <title>{{system_name}}</title>
    {% endif %}
    <link rel="shortcut icon" href="{% static 'assets/default/img/logo.jpg' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/default/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/select2/dist/css/select2.min.css' %}">
    {% comment %} css regarding datatables {% endcomment %}
    
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.0/css/dataTables.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/3.0.1/css/buttons.dataTables.min.css">
    {% comment %} scripts regarding data tables {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://cdn.datatables.net/2.1.0/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.0/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.0/js/buttons.dataTables.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.0/js/buttons.print.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.0.0/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.0/js/dataTables.responsive.js"></script>
    <script src="https://cdn.datatables.net/responsive/3.0.0/js/responsive.dataTables.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.5.0/js/dataTables.rowGroup.js"></script>
    <script src="https://cdn.datatables.net/rowgroup/1.5.0/js/rowGroup.dataTables.js"></script>
    {% comment %}  {% endcomment %}
    <script src="https://cdn.datatables.net/rowgroup/1.4.1/js/dataTables.rowGroup.min.js" ></script>
    <script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/select2/dist/js/select2.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/default/js/script.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/default/js/vfs_fonts.js' %}"></script>
    <style>
        
        .modal-sub-footer {
            display: flex;
            flex-wrap: wrap;
            flex-shrink: 0;
            align-items: center;
            justify-content: flex-end;
            padding: 0.75rem;
            border-top: 1px solid #dee2e6;
            border-bottom-right-radius: calc(0.3rem - 1px);
            border-bottom-left-radius: calc(0.3rem - 1px);
        }
        @media (max-width: 576px) {
            .modal-dialog {
                max-width: calc(100% - 1rem);
            }
        }

        @media (min-width: 577px) and (max-width: 768px) {
            .modal-dialog {
                max-width: calc(100% - 3rem);
            }
        }

/* Add more media queries for other screen sizes as needed */

       
        body{
            background-image:url("{% static 'assets/default/img/bg1.jpg' %}");
            background-size:cover;
            background-repeat:no-repeat;
            background-position:center center;
        }
        #userlist_checkbox[type="checkbox"]{
            pointer-events: none;
        }
    </style>
    {% block headerContent %} {% endblock headerContent %}
</head>
<body class="">
    {% if topbar %} {% block TopNavigation %} {% include "topNavigation.html" %} {% endblock TopNavigation %} {% endif %}
    <main class="py-5 mt-4">
        <div class="container mb-3">
            {% if messages %}
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    {% for message in messages %}
                    <div class="alert alert-{% if message.extra_tags %}{{ message.tags|replaceBlank:message.extra_tags|replaceBlank:' '}}{% else %}{{ message.tags }}{% endif %} w-100 rounded-0 mb-2 redirect-msg">
                        <div class="d-flex w-100">
                            <div class="col-auto flex-shrink-1 flex-grow-1">{{ message|safe }}</div>
                            <div class="col-auto text-center">
                                <button class="btn-close btn-sm text-sm" type="button" onclick="$(this).closest('.alert').remove()"></button>
                            </div>
                        </div>                        
                    </div>
                    {% if message.extra_tags != 'stay' %}
                    <script>
                        $(function(){
                            if($('.redirect-msg').length >0){
                                setTimeout(()=>{
                                    $('.redirect-msg').hide('slideUp')
                                    setTimeout(()=>{
                                        $('.redirect-msg').remove()
                                    },3000)
                                },5000)
                            }
                        })
                    </script>
                    {% endif %}{% endfor %}
            </div>
        </div>{% endif %}{% block pageContent %} {% endblock pageContent %}
    </main>
    {% block ScriptBlock %} {% endblock ScriptBlock %}

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" c aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Transaction Form</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
             <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

    <div class="modal fade" id="uni_modal" tabindex="-1" role='dialog' aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
            <div class="modal-content rounded-0">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn  btn-sm btn-flat btn-primary rounded-0" id='submit' onclick="$('#uni_modal form').submit()">Save</button>
                    <button type="button" class="btn btn-sm btn-flat btn-light border rounded-0" data-bs-dismiss="modal">Cancel</button>
                </div>
                <div class="modal-sub-footer">
                    <button type="button" class="btn btn-sm btn-flat btn-light border rounded-0" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
        <div class="modal fade" id="confirm_modal" aria-hidden="true" tabindex="-1" role='dialog' aria-labelledby="confirmModalLabel">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg" role="document">
                <div class="modal-content rounded-0">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmModalLabel">Confirmation</h5>
                    </div>
                    <div class="modal-body">
                        <div id="delete_content"></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-flat btn-primary rounded-0" id='confirm' onclick="">Continue</button>
                        <button type="button" class="btn btn-sm btn-flat btn-light border rounded-0" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="viewer_modal" role='dialog'>
            <div class="modal-dialog modal-fullscreen" role="document">
                <div class="modal-content rounded-0 bg-transparent">
                    <div class="modal-body bg-transparent d-flex flex-column w-100 h-100 align-items-center justify-content-center">
                        <div class="text-end w-100 px-5">
                            <a class="text-decoration-none text-light" href="javascript:void(0)" data-bs-dismiss="modal"><i class="fa fa-times fs-3"></i></a>
                        </div>
                        <div id="img-viewer" class="w-75 h-75 bg-dark overflow-auto">
                            <img src="" class="image-thumbnail" id="img-viewer-field" />
                        </div>
                        <div class="w-25 d-flex justify-content-center pt-3">
                            <div class="input-group mb-3">
                                <button class="btn btn-dark bg-gradient btn-sm text-light" type="button" id="zoom-minus"><i class="fa fa-minus"></i></button>
                                <input type="text" id="zoom-value" class="form-control form-control-sm rounded-0 w-25 bg-dark bg-gradient border-dark text-light text-center" value="100" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1" readonly>
                                <button class="btn btn-dark bg-gradient btn-sm text-light" type="button" id="zoom-plus"><i class="fa fa-plus"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        const loader = $('<div>')
        loader.attr('id','pre-loader')
        loader.html('<div class="lds-facebook"><div></div><div></div><div></div><div></div>')
        window.start_loader = function(){
            $('body').removeClass('loading')
            if ($('#pre-loader').length > 0)
                $('pre-loader').remove();
            $('body').append(loader)
            $('body').addClass('loading')
        }
        window.end_loader = function(){
            if($('#pre-loader').length > 0)
                $('#pre-loader').remove();
            $('body').removeClass('loading')
        }
        window.form_modal = function($url = ''){
            start_loader()
            $.ajax({
                url:$url,
                error: err =>{
                    alert("An error occured")
                },
                success: function(resp){
                    if(resp){
                        $('#myModal .modal-body').html(resp)
                        $('#myModal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            })
        }
        window.uni_modal = function($title = '', $url = '',$size = ''){
            start_loader()
            $.ajax({
                url:$url,
                error: err =>{
                    alert("An error occured")
                },
                success: function(resp){
                    if(resp){
                        $('#uni_modal .modal-title').html($title)
                        $('#uni_modal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#uni_modal").modal('show')
                        end_loader()
                    }
                }
            })
        }
        window._conf = function($msg = '', $func = '', $params = []) {
            $('#confirm_modal #confirm').attr('onclick', $func + "(" + $params.join(',') + ")")
            $('#confirm_modal .modal-body').html($msg)
            $('#confirm_modal').modal('show')
        }
    </script>
</body>
</html>

templates/topNavigation.html
{% load static %}
<header>
    <style>
        #intro {
            /* Margin to fix overlapping fixed navbar */
            margin-top: 58px;
        }
        
        @media (max-width: 991px) {
            #intro {
                /* Margin to fix overlapping fixed navbar */
                margin-top: 45px;
            }
        }
        #uni_modal .modal-sub-footer{
            display:none;
        }
    </style>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-gradient fixed-top shadow border-bottom">
        <div class="container">
            <!-- Navbar brand -->
            <a class="navbar-brand"  href="{% url 'core:user-list' %}">
            {% if page_title %}
                <b>{{page_name}}</b>
            {% else %}
                <b>{{system_name}}</b>
            {% endif %}
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarExample01" aria-controls="navbarExample01" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarExample01">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" id="topNav">
                    {% if request.user.staffuser or request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'core:user-list' %}">Users</a>
                    </li> 
                    {% endif %}
                    
                   
                    {% if options %}
                        {% for option in options %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href='javascript:void(0)' id="new_form_{{option.0}}">{{option.1}}</a>
                            </li>  
                        {% endfor %}
                    {% endif %}
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'recycle-bin' %}">Recycle Bin</a>
                    </li>  {% endcomment %}
                </ul>

                <ul class="navbar-nav d-flex flex-row">
                    {% if request.user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link"  href="{% url 'admin:index' %}"><b>Howdy, {{request.user}}</b><a>
                    </li>
                    {% endif %}
                    {% if request.user.is_active %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'core:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'core:login-page' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<script>
    $(function() {
        $('#new_form_manage_s_p').click(function(){
            $.ajax({
                url: "{% url 'accounts:manage-sales-purchase'  %}",
                method: 'GET',
                data: {
                    'user_id': {{user.id}},
                },
                error: err =>{
                        alert("An error occured")
                    },
                success: function(resp){
                    if(resp){
                        
                        $('#myModal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            });
        })
         $('#new_form_manage_transactions').click(function(){
            $.ajax({
                url: "{% url 'accounts:manage-transaction'  %}",
                method: 'GET',
                data: {
                    'user_id': {{user.id}},
                },
                error: err =>{
                        alert("An error occured")
                    },
                success: function(resp){
                    if(resp){
                        
                        $('#myModal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            });
        })
         $('#new_form_manage_conversion').click(function(){
            $.ajax({
                url: "{% url 'accounts:conversion'  %}",
                method: 'GET',
                data: {
                    'user_id': {{user.id}},
                },
                error: err =>{
                        alert("An error occured")
                    },
                success: function(resp){
                    if(resp){
                        
                        $('#myModal .modal-body').html(resp)
                        
                        $('#uni_modal').modal({
                            backdrop:'static',
                            keyboard:false,
                            focus:true
                        })
                        $("#myModal").modal('show')
                        end_loader()
                    }
                }
            });
        })
        $('#new_form_product').click(function(){
            window.location.href = "{% url 'accounts:products-pk' pk=user.id %}"
        })
        $('#new_form_parties').click(function(){
            window.location.href = "{% url 'accounts:user-detail-pk' pk=user.id %}"
        })
        $('#topNav .nav-link').each(function() {
            var current = '{{ request.get_full_path | urlencode }}'
            if (current == $(this).attr('href')) {
                $(this).parent().addClass('active')
            }
        })
       
    })
</script>